import { describe, expect, it } from 'vitest'
import { buildInsertPayload, insertOmitBehaviour } from './cell-value.js'

/** A serial primary key as Postgres actually reports it: `bigint`, not `serial`. */
const ID = { name: 'id', dataType: 'int8', nullable: false, autoGenerated: true, hasDefault: true }
const EMAIL = { name: 'email', dataType: 'text', nullable: false }
const NOTE = { name: 'note', dataType: 'text', nullable: true }
const CREATED = { name: 'created_at', dataType: 'timestamptz', nullable: false, hasDefault: true }

describe('insertOmitBehaviour', () => {
  it('names what happens to each blank field', () => {
    expect(insertOmitBehaviour(ID, ['id'])).toBe('auto')
    expect(insertOmitBehaviour(CREATED, ['id'])).toBe('default')
    expect(insertOmitBehaviour(NOTE, ['id'])).toBe('null')
    expect(insertOmitBehaviour(EMAIL, ['id'])).toBe('required')
  })

  it('does not need the primary key to spot a generated column', () => {
    // The catalog flag stands on its own; the old heuristic only fired for
    // columns that were both in the PK and typed `serial`, which is nearly none.
    expect(insertOmitBehaviour({ ...ID, name: 'seq_no' }, [])).toBe('auto')
  })
})

describe('buildInsertPayload', () => {
  const cols = [ID, EMAIL, NOTE, CREATED]

  it('omits a generated column left blank, so the sequence decides', () => {
    const r = buildInsertPayload(cols, ['id'], { id: '', email: 'a@b.c', note: '', created_at: '' })
    expect(r.ok).toBe(true)
    expect(Object.keys(r.values ?? {})).toEqual(['email'])
  })

  it('sends a generated column the user typed into', () => {
    // Overriding a sequence is legitimate - importing a row that must keep its
    // key, backfilling a gap - and the field is writable precisely for that.
    const r = buildInsertPayload(cols, ['id'], { id: '42', email: 'a@b.c', note: '', created_at: '' })
    expect(r.ok).toBe(true)
    expect(r.values?.id).toBe(42)
    expect(r.values?.email).toBe('a@b.c')
  })

  it('still rejects a value the column cannot hold', () => {
    const r = buildInsertPayload(cols, ['id'], { id: 'not-a-number', email: 'a@b.c' })
    expect(r.ok).toBe(false)
    expect(r.message).toContain('id')
  })

  it('lets an all-generated table insert with nothing filled in', () => {
    const r = buildInsertPayload([ID], ['id'], { id: '' })
    expect(r.ok).toBe(true)
    expect(r.values).toEqual({})
  })
})
