/// License system — Ed25519 signed keys + 5-day trial.
///
/// Key format:  <base64url_message>.<base64url_64_byte_signature>
/// Message:     "v1:{email}:{plan}:{iat}:{exp}"   (UTF-8, exp=0 means lifetime)
///
/// After first activation the decoded data is written to:
///   <app_data_dir>/license.json
///
/// Trial is tracked in TWO locations (8 LE bytes = u64 unix timestamp of first launch):
///   <app_data_dir>/.trial        — removed on a full uninstall
///   <home>/.stroke/trial         — survives uninstall, so reinstalling does NOT
///                                  grant a fresh trial. The earliest timestamp
///                                  across both wins, and both are repaired on read.
///   (For tamper-proof enforcement across full disk wipes, register the trial
///    start server-side keyed by device_id — the API scaffolding already exists.)
///
/// -------------------------------------------------------------------
/// SETUP: run  `node scripts/license-tool.mjs keygen`  once.
/// Copy the printed public key hex into PUBLIC_KEY_HEX below, then rebuild.
/// -------------------------------------------------------------------
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};
use std::{
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

const STROKE_API: &str = "https://stroke.click/api/license";

// ── Generated by `node scripts/license-tool.mjs keygen` ─────────────────────
pub const PUBLIC_KEY_HEX: &str =
    "b5f14fed4694302a767e32c4e6a50ba0074c4e50f5198ad781de00d0e8ba8771";

pub const TRIAL_DAYS: i64 = 17;
const LICENSE_FILE: &str = "license.json";
const TRIAL_FILE: &str = ".trial";

// ── Revocation list ───────────────────────────────────────────────────────────
// Each entry is the hex-encoded SHA-256 of the full license key string.
// To revoke a key:
//   1. Run: node scripts/license-tool.mjs revoke <KEY>
//   2. Copy the printed hash into this array.
//   3. Rebuild and ship an app update.
//
// Note: revocation only takes effect after the user installs the update.
// For immediate remote revocation you'll need the server endpoint (coming later).
const REVOKED_KEY_HASHES: &[&str] = &[
    "ed13c9edc3bea01c6f82a415a10b21f85b85f829004f473cb78e8cd10056059f", // revoked 2026-06-05 (case: LIC-REV-2026-06-05-01)
];

// ── Data types ────────────────────────────────────────────────────────────────

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct LicenseFile {
    pub version: u8,
    /// The raw key string the user pasted in
    pub key: String,
    pub email: String,
    pub plan: String,
    pub issued_at: u64,
    /// None / missing field → lifetime license
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<u64>,
    pub device_id: String,
    pub activated_at: u64,
    /// Unix timestamp of the last successful server check (0 = never checked).
    #[serde(default)]
    pub last_check_at: u64,
}

#[derive(serde::Serialize, Debug, Clone)]
#[serde(tag = "status")]
pub enum LicenseStatus {
    /// Active paid license
    Valid {
        email: String,
        plan: String,
        issued_at: u64,
        expires_at: Option<u64>,
    },
    /// Free trial still running
    Trial { days_remaining: i64 },
    /// Trial period over, no license
    TrialExpired,
    /// App data dir inaccessible (should not normally happen)
    Error { message: String },
}

// ── Path helpers ──────────────────────────────────────────────────────────────

pub fn license_path(data_dir: &Path) -> PathBuf {
    data_dir.join(LICENSE_FILE)
}

pub fn trial_path(data_dir: &Path) -> PathBuf {
    data_dir.join(TRIAL_FILE)
}

/// The user's home directory, cross-platform (HOME on unix/macOS, USERPROFILE on Windows).
fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
}

/// All locations the trial start is mirrored to. The app-data copy is wiped on
/// uninstall; the home-dir copy survives, so a reinstall can't reset the trial.
fn trial_paths(data_dir: &Path) -> Vec<PathBuf> {
    let mut paths = vec![trial_path(data_dir)];
    if let Some(home) = home_dir() {
        paths.push(home.join(".stroke").join("trial"));
    }
    paths
}

// ── Device fingerprint ────────────────────────────────────────────────────────

/// Returns a stable SHA-256 hex fingerprint for this machine.
pub fn device_id() -> String {
    let raw = machine_id_raw();
    let mut h = Sha256::new();
    h.update(raw.as_bytes());
    hex::encode(h.finalize())
}

fn machine_id_raw() -> String {
    #[cfg(target_os = "linux")]
    {
        if let Ok(s) = std::fs::read_to_string("/etc/machine-id") {
            let t = s.trim().to_string();
            if !t.is_empty() {
                return t;
            }
        }
        if let Ok(s) = std::fs::read_to_string("/var/lib/dbus/machine-id") {
            let t = s.trim().to_string();
            if !t.is_empty() {
                return t;
            }
        }
    }
    #[cfg(target_os = "macos")]
    {
        if let Ok(out) = std::process::Command::new("ioreg")
            .args(["-rd1", "-c", "IOPlatformExpertDevice"])
            .output()
        {
            if let Ok(s) = String::from_utf8(out.stdout) {
                for line in s.lines() {
                    if line.contains("IOPlatformUUID") {
                        if let Some(uuid) = line.split('"').nth(3) {
                            return uuid.to_string();
                        }
                    }
                }
            }
        }
    }
    #[cfg(target_os = "windows")]
    {
        if let Ok(out) = std::process::Command::new("reg")
            .args([
                "query",
                "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography",
                "/v",
                "MachineGuid",
            ])
            .output()
        {
            if let Ok(s) = String::from_utf8(out.stdout) {
                for line in s.lines() {
                    if line.contains("MachineGuid") {
                        if let Some(guid) = line.split_whitespace().last() {
                            return guid.to_string();
                        }
                    }
                }
            }
        }
    }
    // Fallback: try platform-appropriate env vars then /etc/hostname.
    // COMPUTERNAME is the correct Windows variable; HOSTNAME is POSIX-standard.
    std::env::var("COMPUTERNAME")                          // Windows
        .or_else(|_| std::env::var("HOSTNAME"))           // Linux/macOS shell env
        .or_else(|_| std::fs::read_to_string("/etc/hostname").map(|s| s.trim().to_string()))
        .unwrap_or_else(|_| "unknown-host".to_string())
}

// ── Trial management ──────────────────────────────────────────────────────────

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Reads the trial start across all mirror locations and returns `days_remaining`
/// (negative = expired). The EARLIEST timestamp found wins — so deleting one copy
/// (e.g. uninstalling, which wipes app-data) can't grant a fresh trial while the
/// home-dir copy survives. Every location is (re)written with the winning start so
/// a missing/newer copy is repaired on each launch.
pub fn trial_days_remaining(data_dir: &Path) -> i64 {
    let paths = trial_paths(data_dir);

    let mut earliest: Option<u64> = None;
    for p in &paths {
        if let Ok(bytes) = std::fs::read(p) {
            if let Ok(arr) = <[u8; 8]>::try_from(bytes.as_slice()) {
                let t = u64::from_le_bytes(arr);
                earliest = Some(earliest.map_or(t, |e| e.min(t)));
            }
        }
    }

    // First launch on this device (or every copy was removed) — start now.
    let start_secs = earliest.unwrap_or_else(now_secs);

    // Propagate/repair the winning start to every location.
    for p in &paths {
        if let Some(dir) = p.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        let _ = std::fs::write(p, start_secs.to_le_bytes());
    }

    let elapsed_days = (now_secs().saturating_sub(start_secs) / 86_400) as i64;
    TRIAL_DAYS - elapsed_days
}

/// The earliest trial start recorded across local mirrors, without writing.
/// `None` if no local trial file exists yet (e.g. a fresh install).
fn local_trial_start(data_dir: &Path) -> Option<u64> {
    let mut earliest: Option<u64> = None;
    for p in trial_paths(data_dir) {
        if let Ok(bytes) = std::fs::read(&p) {
            if let Ok(arr) = <[u8; 8]>::try_from(bytes.as_slice()) {
                let t = u64::from_le_bytes(arr);
                earliest = Some(earliest.map_or(t, |e| e.min(t)));
            }
        }
    }
    earliest
}

/// Phone home to sync the trial clock with the server (earliest-wins). The
/// server records the start the first time it sees this device and always
/// returns the earliest known start — so a reinstall or disk wipe can't hand
/// out a fresh trial. On success the authoritative start is written to every
/// local mirror so the next local check reflects it. No-op when offline.
pub async fn reconcile_trial(data_dir: &Path) {
    let local = local_trial_start(data_dir);
    if let Some(server_start) = api_trial(&device_id(), local).await {
        for p in trial_paths(data_dir) {
            if let Some(dir) = p.parent() {
                let _ = std::fs::create_dir_all(dir);
            }
            let _ = std::fs::write(&p, server_start.to_le_bytes());
        }
    }
}

/// DEBUG ONLY — write a trial start timestamp N days in the past so the UI
/// shows "N days elapsed" without waiting for real time to pass.
#[cfg(debug_assertions)]
pub fn debug_set_trial_days_ago(data_dir: &Path, days_ago: u64) -> Result<(), String> {
    let fake_start = now_secs().saturating_sub(days_ago * 86_400);
    for p in trial_paths(data_dir) {
        if let Some(dir) = p.parent() {
            std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
        }
        std::fs::write(&p, fake_start.to_le_bytes()).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// DEBUG ONLY — delete every trial mirror so the next check starts a fresh trial.
#[cfg(debug_assertions)]
pub fn debug_reset_trial(data_dir: &Path) -> Result<(), String> {
    for p in trial_paths(data_dir) {
        if p.exists() {
            std::fs::remove_file(&p).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

// ── Signature verification ────────────────────────────────────────────────────

#[derive(Debug)]
pub struct ParsedKey {
    pub email: String,
    pub plan: String,
    pub issued_at: u64,
    pub expires_at: Option<u64>,
}

/// Return the hex SHA-256 of a key string — used to populate REVOKED_KEY_HASHES.
pub fn key_hash(key: &str) -> String {
    let mut h = Sha256::new();
    h.update(key.as_bytes());
    hex::encode(h.finalize())
}

/// Verify an `<base64url_msg>.<base64url_sig>` license key.
/// Returns the parsed payload on success, or an error string.
pub fn verify_key(key: &str) -> Result<ParsedKey, String> {
    // Check revocation list first
    let hash = key_hash(key);
    if REVOKED_KEY_HASHES.contains(&hash.as_str()) {
        return Err("this license key has been revoked".to_string());
    }

    // Decode public key
    let pk_bytes: [u8; 32] = hex::decode(PUBLIC_KEY_HEX)
        .map_err(|_| "invalid public key constant (not hex)".to_string())?
        .try_into()
        .map_err(|_| "public key must be 32 bytes".to_string())?;

    // Reject placeholder key
    if pk_bytes == [0u8; 32] {
        return Err("Public key not configured — run `node scripts/license-tool.mjs keygen` and update PUBLIC_KEY_HEX in license.rs".to_string());
    }

    let verifying_key =
        VerifyingKey::from_bytes(&pk_bytes).map_err(|e| format!("bad public key: {e}"))?;

    // Split key into message + signature
    let (msg_b64, sig_b64) = key
        .split_once('.')
        .ok_or_else(|| "invalid key format (expected <payload>.<signature>)".to_string())?;

    let msg_bytes = URL_SAFE_NO_PAD
        .decode(msg_b64.trim())
        .map_err(|_| "key payload is not valid base64url".to_string())?;

    let sig_bytes = URL_SAFE_NO_PAD
        .decode(sig_b64.trim())
        .map_err(|_| "key signature is not valid base64url".to_string())?;

    let sig_arr: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| "signature must be 64 bytes".to_string())?;
    let signature = Signature::from_bytes(&sig_arr);

    // Verify Ed25519 signature
    verifying_key
        .verify(&msg_bytes, &signature)
        .map_err(|_| "invalid license signature — key may be forged or corrupted".to_string())?;

    // Parse message "v1:{email}:{plan}:{iat}:{exp}"
    let msg_str = String::from_utf8(msg_bytes)
        .map_err(|_| "message payload is not UTF-8".to_string())?;

    let parts: Vec<&str> = msg_str.splitn(5, ':').collect();
    if parts.len() != 5 || parts[0] != "v1" {
        return Err("unrecognised license message format".to_string());
    }

    let email = parts[1].to_string();
    let plan = parts[2].to_string();
    let iat: u64 = parts[3]
        .parse()
        .map_err(|_| "invalid issued_at timestamp".to_string())?;
    let exp_raw: u64 = parts[4]
        .parse()
        .map_err(|_| "invalid expires_at timestamp".to_string())?;
    let expires_at = if exp_raw == 0 { None } else { Some(exp_raw) };

    // Check expiry
    if let Some(exp) = expires_at {
        if now_secs() > exp {
            return Err("license has expired".to_string());
        }
    }

    Ok(ParsedKey {
        email,
        plan,
        issued_at: iat,
        expires_at,
    })
}

// ── License file I/O ──────────────────────────────────────────────────────────

pub fn load_license(data_dir: &Path) -> Option<LicenseFile> {
    let raw = std::fs::read_to_string(license_path(data_dir)).ok()?;
    serde_json::from_str(&raw).ok()
}

pub fn save_license(data_dir: &Path, lic: &LicenseFile) -> Result<(), String> {
    std::fs::create_dir_all(data_dir).map_err(|e| e.to_string())?;
    let json = serde_json::to_string_pretty(lic).map_err(|e| e.to_string())?;
    std::fs::write(license_path(data_dir), json).map_err(|e| e.to_string())
}

pub fn delete_license(data_dir: &Path) -> Result<(), String> {
    let p = license_path(data_dir);
    if p.exists() {
        std::fs::remove_file(p).map_err(|e| e.to_string())?;
    }
    Ok(())
}

// ── Hostname helper ───────────────────────────────────────────────────────────

fn hostname() -> String {
    std::env::var("COMPUTERNAME")
        .or_else(|_| std::env::var("HOSTNAME"))
        .or_else(|_| std::fs::read_to_string("/etc/hostname").map(|s| s.trim().to_string()))
        .unwrap_or_else(|_| "unknown".to_string())
}

// ── Remote API calls ──────────────────────────────────────────────────────────

fn http_client() -> reqwest::Client {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .unwrap_or_default()
}

/// POST /api/license/activate — registers this device with the server.
/// Returns the server JSON on success, or an error string.
/// On network failure returns Ok(None) so the caller can apply an offline grace.
pub async fn api_activate(
    key: &str,
    device_id: &str,
) -> Result<Option<serde_json::Value>, String> {
    let body = serde_json::json!({
        "key": key,
        "device_id": device_id,
        "hostname": hostname(),
    });
    let resp = match http_client()
        .post(format!("{STROKE_API}/activate"))
        .json(&body)
        .send()
        .await
    {
        Ok(r) => r,
        Err(_) => return Ok(None), // network unreachable → offline grace
    };
    let json: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
    if json.get("valid").and_then(|v| v.as_bool()).unwrap_or(false) {
        Ok(Some(json))
    } else {
        let err = json
            .get("error")
            .and_then(|v| v.as_str())
            .unwrap_or("unknown_error")
            .to_string();
        Err(err)
    }
}

/// POST /api/license/check — phone-home to detect server-side revocation.
/// Returns `true` if still valid, `false` if revoked/invalid.
/// Returns `None` on network error (caller should skip and retry later).
pub async fn api_check(key: &str, device_id: &str) -> Option<bool> {
    let body = serde_json::json!({ "key": key, "device_id": device_id });
    let resp = http_client()
        .post(format!("{STROKE_API}/check"))
        .json(&body)
        .send()
        .await
        .ok()?;
    let json: serde_json::Value = resp.json().await.ok()?;
    Some(json.get("valid").and_then(|v| v.as_bool()).unwrap_or(false))
}

/// POST /api/license/trial — register/sync this device's trial start.
/// Sends the local start (if any) so the server can keep the earliest; returns
/// the server's authoritative start (unix seconds), or None on network error.
pub async fn api_trial(device_id: &str, local_started_at: Option<u64>) -> Option<u64> {
    let mut body = serde_json::json!({ "device_id": device_id, "hostname": hostname() });
    if let Some(s) = local_started_at {
        body["started_at"] = serde_json::json!(s);
    }
    let resp = http_client()
        .post(format!("{STROKE_API}/trial"))
        .json(&body)
        .send()
        .await
        .ok()?;
    let json: serde_json::Value = resp.json().await.ok()?;
    json.get("started_at").and_then(|v| v.as_u64())
}

/// POST /api/license/deactivate — releases the seat on the server.
/// Fire-and-forget; silently ignores errors.
pub async fn api_deactivate(key: &str, device_id: &str) {
    let body = serde_json::json!({ "key": key, "device_id": device_id });
    let _ = http_client()
        .post(format!("{STROKE_API}/deactivate"))
        .json(&body)
        .send()
        .await;
}

// ── High-level status check ───────────────────────────────────────────────────

pub fn check_status(data_dir: &Path) -> LicenseStatus {
    // 1. Valid stored license?
    if let Some(lic) = load_license(data_dir) {
        // Re-verify signature and device binding
        match verify_key(&lic.key) {
            Ok(parsed) => {
                // Soft device check
                if lic.device_id == device_id() || cfg!(debug_assertions) {
                    return LicenseStatus::Valid {
                        email: parsed.email,
                        plan: parsed.plan,
                        issued_at: parsed.issued_at,
                        expires_at: parsed.expires_at,
                    };
                }
                // Device mismatch — treat as expired trial so they can re-activate
            }
            Err(_) => {
                // Corrupted / tampered license file — remove it
                let _ = delete_license(data_dir);
            }
        }
    }

    // 2. Trial
    let days = trial_days_remaining(data_dir);
    if days > 0 {
        LicenseStatus::Trial {
            days_remaining: days,
        }
    } else {
        LicenseStatus::TrialExpired
    }
}
