<script>
  import { onDestroy } from "svelte";
  import { listen } from "@tauri-apps/api/event";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import * as Select from "$lib/components/ui/select/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Checkbox } from "$lib/components/ui/checkbox/index.js";
  import { toast } from "$lib/components/ui/sonner/toast.svelte.js";
  import Loader from "@lucide/svelte/icons/loader";
  import FileUp from "@lucide/svelte/icons/file-up";
  import FileText from "@lucide/svelte/icons/file-text";
  import StopCircle from "@lucide/svelte/icons/stop-circle";
  import { importRows, importCancel, readFile } from "$lib/api.js";
  import {
    autoMapFields,
    parseImportText,
    toTypedRows,
  } from "$lib/import-parse.js";
  import { cn } from "$lib/utils.js";

  /** @typedef {{ name: string, dataType?: string, data_type?: string, nullable?: boolean, autoGenerated?: boolean, hasDefault?: boolean }} Column */

  let {
    open = $bindable(false),
    schema = "",
    table = "",
    /** @type {Column[]} */
    columns = [],
    /** @type {string[]} */
    primaryKey = [],
    /** Called after a successful import so the grid can refetch. */
    onimported = async () => {},
  } = $props();

  // ── Source ──────────────────────────────────────────────────────────────────
  let fileName = $state("");
  let rawText = $state("");
  let parseError = $state("");

  // ── Parse options ───────────────────────────────────────────────────────────
  /** @type {'auto'|'delimited'|'json'} */
  let format = $state("auto");
  let delimiter = $state("");
  let hasHeader = $state(true);
  let nullText = $state("");
  let emptyAsNull = $state(true);
  let parseNumbers = $state(true);

  // ── Target ──────────────────────────────────────────────────────────────────
  /** @type {Record<string, string>} column name -> source field */
  let mapping = $state({});
  /** @type {'error'|'skip'|'update'} */
  let conflict = $state("error");
  /** @type {string[]} */
  let conflictColumns = $state([]);
  let abortOnError = $state(true);

  // ── Run ─────────────────────────────────────────────────────────────────────
  /** @type {'idle'|'running'|'done'} */
  let phase = $state("idle");
  let stopping = $state(false);
  /** @type {import('$lib/api.js').ImportRowsResult|null} */
  let result = $state(null);
  let showErrors = $state(false);
  /** @type {{level: string, message: string}[]} */
  let logs = $state([]);
  /** @type {(() => void)|null} */
  let unlisten = null;

  const colType = (/** @type {Column} */ c) => c.dataType ?? c.data_type ?? "";

  /**
   * Parsing is pure and fast, so it re-runs whenever an option changes rather
   * than being triggered by hand - the preview then always reflects the
   * settings above it.
   */
  const parsed = $derived.by(() => {
    if (!rawText) return { fields: [], rows: [], format: "delimited", delimiter: "" };
    try {
      const out = parseImportText(rawText, {
        format,
        delimiter: delimiter || undefined,
        hasHeader,
      });
      parseError = "";
      return out;
    } catch (e) {
      parseError = String(/** @type {any} */ (e)?.message ?? e);
      return { fields: [], rows: [], format: "delimited", delimiter: "" };
    }
  });

  const mappedColumns = $derived(
    columns.map((c) => c.name).filter((name) => mapping[name]),
  );

  /**
   * Columns the database will not fill in for you: NOT NULL, no default, not
   * auto-generated. Leaving one unmapped fails every row, so the dialog says so
   * before the import runs rather than after. Mirrors the backend's own check.
   */
  const missingRequired = $derived(
    columns
      .filter(
        (c) =>
          c.nullable === false &&
          !c.hasDefault &&
          !c.autoGenerated &&
          !mapping[c.name],
      )
      .map((c) => c.name),
  );

  const previewRows = $derived(parsed.rows.slice(0, 8));

  const canRun = $derived(
    mappedColumns.length > 0 &&
      parsed.rows.length > 0 &&
      !parseError &&
      missingRequired.length === 0 &&
      (conflict !== "update" || conflictColumns.length > 0) &&
      phase !== "running",
  );

  // Re-map whenever a new file is parsed into a different set of fields.
  $effect(() => {
    const fields = parsed.fields;
    if (fields.length === 0) return;
    const names = columns.map((c) => c.name);
    mapping = autoMapFields(names, fields);
  });

  // Default the conflict key to the primary key - the only choice that is
  // right most of the time, and the one a user would otherwise have to
  // re-enter on every import.
  $effect(() => {
    if (conflictColumns.length === 0 && primaryKey.length > 0) {
      conflictColumns = [...primaryKey];
    }
  });

  async function startLog() {
    stopLog();
    unlisten = await listen("import-log", (/** @type {any} */ e) => {
      logs = [...logs.slice(-199), e.payload];
    });
  }
  function stopLog() {
    unlisten?.();
    unlisten = null;
  }
  onDestroy(stopLog);

  async function pickFile() {
    const { open: openDialog } = await import("@tauri-apps/plugin-dialog");
    const path = await openDialog({
      multiple: false,
      filters: [
        { name: "Data", extensions: ["csv", "tsv", "txt", "json", "jsonl", "ndjson"] },
      ],
    });
    if (typeof path !== "string") return;
    try {
      rawText = await readFile(path);
      fileName = path.split(/[/\\]/).pop() ?? path;
      // A fresh file gets a fresh guess; keeping the old delimiter would parse
      // a tab file with the comma the previous one needed.
      delimiter = "";
      format = "auto";
      result = null;
      phase = "idle";
    } catch (e) {
      toast.error("Could not read the file", { description: String(e) });
    }
  }

  async function run() {
    if (!canRun) return;
    const targetColumns = mappedColumns;
    const rows = toTypedRows(parsed.rows, parsed.fields, mapping, targetColumns, {
      nullText,
      emptyAsNull,
      parseNumbers,
    });

    phase = "running";
    stopping = false;
    result = null;
    showErrors = false;
    logs = [];
    await startLog();
    try {
      const res = await importRows(schema || null, table, targetColumns, rows, {
        conflict,
        conflictColumns: conflict === "error" ? [] : conflictColumns,
        abortOnError,
      });
      result = res;
      phase = "done";
      if (res.rolledBack) {
        toast.warning("Import rolled back, nothing was changed");
      } else if (res.failed > 0) {
        toast.warning(`Imported ${res.inserted} row(s), ${res.failed} failed`);
      } else if (res.cancelled) {
        toast.info(`Import cancelled after ${res.inserted} row(s)`);
      } else {
        toast.success(`Imported ${res.inserted} row(s)`);
      }
      if (res.inserted > 0) await onimported();
    } catch (e) {
      phase = "idle";
      toast.error("Could not import", {
        description: String(/** @type {any} */ (e)?.message ?? e),
      });
    } finally {
      stopLog();
      stopping = false;
    }
  }

  function stop() {
    // Stay in `running` until the backend reports back, so the result panel can
    // say what actually landed instead of leaving the user guessing.
    stopping = true;
    importCancel().catch(() => {});
    toast.info("Stopping the import…");
  }

  function reset() {
    fileName = "";
    rawText = "";
    parseError = "";
    result = null;
    phase = "idle";
    stopping = false;
    logs = [];
    mapping = {};
  }

  const CONFLICT_OPTIONS = [
    { value: "error", label: "Report an error" },
    { value: "skip", label: "Keep the existing row" },
    { value: "update", label: "Update the existing row" },
  ];

  const DELIMITERS = [
    { value: "", label: "Detect" },
    { value: ",", label: "Comma" },
    { value: "\t", label: "Tab" },
    { value: ";", label: "Semicolon" },
    { value: "|", label: "Pipe" },
  ];
</script>

<Dialog.Root
  bind:open
  onOpenChange={(v) => {
    if (!v) reset();
  }}
>
  <Dialog.Content class="flex max-h-[85vh] max-w-3xl flex-col gap-0 overflow-hidden p-0">
    <Dialog.Header class="border-b border-border/60 px-5 py-4">
      <Dialog.Title class="text-ui-sm">Import data</Dialog.Title>
      <Dialog.Description class="text-ui-2xs">
        Load rows from a CSV, TSV or JSON file into
        <span class="font-mono text-foreground">{schema ? `${schema}.` : ""}{table}</span>.
      </Dialog.Description>
    </Dialog.Header>

    <div class="min-h-0 flex-1 overflow-y-auto px-5 py-4">
      {#if phase === "done" && result}
        <!-- ── Result ── -->
        <div
          class={cn(
            "rounded-lg border p-4",
            result.failed === 0 && !result.rolledBack
              ? "border-success/30 bg-success/8"
              : "border-warning/30 bg-warning/8",
          )}
        >
          <p class="text-ui-xs font-semibold text-foreground">
            {#if result.rolledBack}
              Rolled back — nothing was imported
            {:else if result.cancelled}
              Import cancelled
            {:else if result.failed > 0}
              Finished with errors
            {:else}
              Import complete
            {/if}
          </p>
          <div class="mt-3 flex gap-5 rounded-lg border border-border/40 bg-background/60 px-3 py-2.5 font-mono text-ui-xs">
            <div>
              <p class="text-ui-3xs uppercase tracking-wide text-muted-foreground">Inserted</p>
              <p class="mt-0.5 font-semibold text-success">{result.inserted}</p>
            </div>
            {#if result.failed > 0}
              <div>
                <p class="text-ui-3xs uppercase tracking-wide text-muted-foreground">Failed</p>
                <p class="mt-0.5 font-semibold text-destructive">{result.failed}</p>
              </div>
            {/if}
            {#if result.skipped > 0}
              <div>
                <p class="text-ui-3xs uppercase tracking-wide text-muted-foreground">Not run</p>
                <p class="mt-0.5 font-semibold text-muted-foreground">{result.skipped}</p>
              </div>
            {/if}
          </div>

          {#if result.errors.length > 0}
            <button
              type="button"
              class="mt-3 text-ui-2xs text-muted-foreground underline"
              onclick={() => (showErrors = !showErrors)}
            >
              {showErrors ? "Hide" : "Show"}
              {result.errors.length} error{result.errors.length === 1 ? "" : "s"}
            </button>
            {#if showErrors}
              <div class="mt-2 max-h-48 overflow-y-auto rounded-lg border border-border/40 bg-background p-2.5">
                {#each result.errors as err (err.row)}
                  <p class="font-mono text-ui-3xs text-destructive">
                    <span class="text-muted-foreground">Row {err.row}:</span>
                    {err.message}
                  </p>
                {/each}
              </div>
            {/if}
          {/if}
        </div>
      {:else if !rawText}
        <!-- ── Pick a file ── -->
        <button
          type="button"
          onclick={pickFile}
          class="flex w-full flex-col items-center gap-2 rounded-lg border border-dashed border-border/70 bg-background/40 px-4 py-10 transition-colors hover:border-primary/40 hover:bg-accent/30"
        >
          <FileUp class="size-6 shrink-0 text-muted-foreground" />
          <span class="text-ui-xs font-medium text-foreground">Choose a file</span>
          <span class="text-ui-2xs text-muted-foreground">
            <span class="font-mono">.csv</span>, <span class="font-mono">.tsv</span>,
            <span class="font-mono">.json</span> or <span class="font-mono">.jsonl</span>
          </span>
        </button>
      {:else}
        <!-- ── Options, mapping, preview ── -->
        <div class="flex items-center gap-2 rounded-lg border border-border/60 bg-background/50 px-3 py-2">
          <FileText class="size-3.5 shrink-0 text-muted-foreground" />
          <span class="min-w-0 flex-1 truncate font-mono text-ui-2xs text-foreground">{fileName}</span>
          <span class="shrink-0 text-ui-3xs text-muted-foreground">
            {parsed.rows.length} row{parsed.rows.length === 1 ? "" : "s"}
          </span>
          <Button variant="ghost" size="sm" class="h-7 shrink-0" onclick={pickFile}>Change</Button>
        </div>

        {#if parseError}
          <p class="mt-3 rounded-md border border-destructive/30 bg-destructive/8 px-3 py-2 text-ui-2xs text-destructive">
            {parseError}
          </p>
        {/if}

        {#if parsed.format === "delimited"}
          <div class="mt-4 flex flex-wrap items-end gap-3">
            <label class="flex flex-col gap-1">
              <span class="text-ui-3xs uppercase tracking-wide text-muted-foreground">Delimiter</span>
              <Select.Root type="single" bind:value={delimiter}>
                <Select.Trigger class="h-8 w-32 text-ui-xs">
                  {DELIMITERS.find((d) => d.value === delimiter)?.label ?? "Detect"}
                </Select.Trigger>
                <Select.Content>
                  {#each DELIMITERS as d (d.label)}
                    <Select.Item value={d.value} label={d.label}>{d.label}</Select.Item>
                  {/each}
                </Select.Content>
              </Select.Root>
            </label>
            <label class="flex flex-col gap-1">
              <span class="text-ui-3xs uppercase tracking-wide text-muted-foreground">Null is</span>
              <Input bind:value={nullText} placeholder="(nothing)" class="h-8 w-32 font-mono text-ui-xs" />
            </label>
            <label class="flex h-8 items-center gap-2">
              <Checkbox bind:checked={hasHeader} />
              <span class="text-ui-2xs text-foreground">First row is a header</span>
            </label>
            <label class="flex h-8 items-center gap-2">
              <Checkbox bind:checked={emptyAsNull} />
              <span class="text-ui-2xs text-foreground">Empty is NULL</span>
            </label>
            <label class="flex h-8 items-center gap-2">
              <Checkbox bind:checked={parseNumbers} />
              <span class="text-ui-2xs text-foreground">Convert numbers</span>
            </label>
          </div>
        {/if}

        <!-- Mapping -->
        <p class="mt-5 text-ui-3xs uppercase tracking-wide text-muted-foreground">Columns</p>
        <div class="mt-2 overflow-hidden rounded-lg border border-border/60">
          {#each columns as col (col.name)}
            <div class="flex items-center gap-3 border-b border-border/40 px-3 py-1.5 last:border-b-0">
              <div class="flex min-w-0 flex-1 items-baseline gap-2">
                <span class="truncate font-mono text-ui-2xs text-foreground">{col.name}</span>
                <span class="shrink-0 font-mono text-ui-3xs text-muted-foreground">{colType(col)}</span>
                {#if missingRequired.includes(col.name)}
                  <span class="shrink-0 text-ui-3xs text-destructive">required</span>
                {/if}
              </div>
              <Select.Root type="single" bind:value={mapping[col.name]}>
                <Select.Trigger class="h-7 w-48 shrink-0 font-mono text-ui-2xs">
                  {mapping[col.name] || "Skip"}
                </Select.Trigger>
                <Select.Content>
                  <Select.Item value="" label="Skip">Skip</Select.Item>
                  {#each parsed.fields as field (field)}
                    <Select.Item value={field} label={field}>{field}</Select.Item>
                  {/each}
                </Select.Content>
              </Select.Root>
            </div>
          {/each}
        </div>

        {#if missingRequired.length > 0}
          <p class="mt-2 text-ui-3xs text-destructive">
            Map a field to {missingRequired.join(", ")} — the column is NOT NULL with no default,
            so every row would fail.
          </p>
        {/if}

        <!-- Conflicts -->
        <div class="mt-5 flex flex-wrap items-end gap-3">
          <label class="flex flex-col gap-1">
            <span class="text-ui-3xs uppercase tracking-wide text-muted-foreground">If the row exists</span>
            <Select.Root type="single" bind:value={conflict}>
              <Select.Trigger class="h-8 w-52 text-ui-xs">
                {CONFLICT_OPTIONS.find((o) => o.value === conflict)?.label}
              </Select.Trigger>
              <Select.Content>
                {#each CONFLICT_OPTIONS as o (o.value)}
                  <Select.Item value={o.value} label={o.label}>{o.label}</Select.Item>
                {/each}
              </Select.Content>
            </Select.Root>
          </label>
          {#if conflict === "update"}
            <p class="pb-2 text-ui-3xs text-muted-foreground">
              Matching on
              <span class="font-mono text-foreground">{conflictColumns.join(", ") || "—"}</span>
            </p>
          {/if}
          <label class="flex h-8 items-center gap-2">
            <Checkbox bind:checked={abortOnError} />
            <span class="text-ui-2xs text-foreground">All or nothing</span>
          </label>
        </div>
        <p class="mt-1 text-ui-3xs text-muted-foreground">
          {abortOnError
            ? "The first failure rolls the whole import back."
            : "Bad rows are reported and the rest are kept."}
        </p>

        <!-- Preview -->
        {#if previewRows.length > 0}
          <p class="mt-5 text-ui-3xs uppercase tracking-wide text-muted-foreground">Preview</p>
          <div class="mt-2 overflow-x-auto rounded-lg border border-border/60">
            <table class="w-full border-collapse">
              <thead>
                <tr class="border-b border-border/60 bg-muted/30">
                  {#each parsed.fields as field (field)}
                    <th class="px-2.5 py-1.5 text-left font-mono text-ui-3xs font-medium text-muted-foreground">
                      {field}
                    </th>
                  {/each}
                </tr>
              </thead>
              <tbody>
                {#each previewRows as row, i (i)}
                  <tr class="border-b border-border/30 last:border-b-0">
                    {#each parsed.fields as _field, c (c)}
                      <td class="max-w-48 truncate px-2.5 py-1 font-mono text-ui-3xs text-foreground">
                        {row[c] === null || row[c] === undefined ? "" : String(row[c])}
                      </td>
                    {/each}
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if phase === "running" && logs.length > 0}
          <div class="mt-4 max-h-24 overflow-y-auto rounded-lg border border-border/40 bg-background p-2.5">
            {#each logs as entry, i (i)}
              <p class="font-mono text-ui-3xs text-muted-foreground">{entry.message}</p>
            {/each}
          </div>
        {/if}
      {/if}
    </div>

    <Dialog.Footer class="border-t border-border/60 px-5 py-3">
      {#if phase === "done"}
        <Button variant="outline" size="sm" onclick={reset}>Import another</Button>
        <Button size="sm" onclick={() => (open = false)}>Done</Button>
      {:else if phase === "running"}
        <Button variant="outline" size="sm" disabled={stopping} onclick={stop}>
          <StopCircle class="size-3.5 shrink-0" />
          {stopping ? "Stopping…" : "Stop"}
        </Button>
        <Button size="sm" disabled>
          <Loader class="size-3.5 shrink-0 animate-spin" />Importing…
        </Button>
      {:else}
        <Button variant="outline" size="sm" onclick={() => (open = false)}>Cancel</Button>
        <Button size="sm" disabled={!canRun} onclick={run}>
          Import {parsed.rows.length > 0 ? `${parsed.rows.length} row${parsed.rows.length === 1 ? "" : "s"}` : ""}
        </Button>
      {/if}
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
